### ISSUE TITLE
Handle does not close

### ISSUE THREAD

**Issue by Delagen** [iccicci/rotating-file-stream#11]
While wrote own implementation on TS found that 

https://github.com/iccicci/rotating-file-stream/blob/master/compress.js#L246

does not close handle of file, that cause test failing when removing previous results
 due EPERM with directory is not empty

**Comment by iccicci** [comment]
Thank you,

I'll fix this asap

**Comment by Delagen** [comment]
It simply can be replaced with writeFile call with empty string

**Comment by iccicci** [comment]
That will replace file content.
More than this I have to take care of tests and coverage....

It's a bit more complicated, but I'll fix that asap anyway.

**Comment by Delagen** [comment]
```
fs.writeFile(file, data,{flag:"a"}, callback)
```

**Comment by iccicci** [comment]
Interesting, I missed that.

Thank you
