### ISSUE TITLE
Version 1.2.2 automatically create the folder like 20170531-1617-01-

### ISSUE THREAD

**Issue by DuanPengfei** [iccicci/rotating-file-stream#13]
`// index.js`
![qq20170531-171730 2x](https://cloud.githubusercontent.com/assets/4469502/26625131/c7a41f5c-4625-11e7-9421-f0af298d5825.png)

`// compress.js`
<img width="587" alt="qq20170531-162723 2x" src="https://cloud.githubusercontent.com/assets/4469502/26623642/eafde24e-4620-11e7-8392-0d014a3076ea.png">

`// compress.js`
<img width="669" alt="qq20170531-163101 2x" src="https://cloud.githubusercontent.com/assets/4469502/26623674/fe859e38-4620-11e7-8920-20ed80a20e9e.png">

### Don't use compress option
Didn't send `tmp(options.compress = null)` parameter to `findName`, `findName` will return the result of `this.generator`, like `20170531-1617-01-/Users/someone/.projectName/logs/projectName.error.log`.

Then `move` function use `fs.rename` move `/Users/someone/.projectName/logs/projectName.error.log` to `${process.cwd()}/20170531-1617-01-/Users/someone/.projectName/logs/projectName.error.log`. 

Because of `options.compress` is `false`, so `self.compress(name)` in `callback` will not run.

### Use gzip compress option

Sent `tmp(options.compress = "gzip")` parameter to `findName`, `findName` will return `name` like `/Users/someone/.projectName/logs/projectName.error.log.1.rfs.tmp`.

Then `move` function use `fs.rename` move `/Users/someone/.projectName/logs/projectName.error.log` to `/Users/someone/.projectName/logs/projectName.error.log.1.rfs.tmp`. 

Because of `options.compress` is `true`, so `self.compress(name)` in `callback` will run.

In `compress` function will call `findName` again and didn't send `tmp(options.compress = null)`, so get the result name like `${process.cwd()}/20170531-1617-01-/Users/someone/.projectName/logs/projectName.error.log`.

Then `self.touch` → `self.gzip` also create folder like `${process.cwd()}20170531-1617-01-/Users/someone/.projectName/logs/projectName.error.log`.

### Conclusion
I don't knwo if I understand correctly, the result is the folder like `20170531-1617-01-` will always be created. I don't know it is a feature or bug. Please give me help.

**Comment by iccicci** [comment]
Hi,

it seems you find an options combination which causes a bug.
Can you please show me how do you call the contructor?

Thank you,
iCC

**Comment by DuanPengfei** [comment]
```
const _out = rotatingFileStream(`${os.userInfo().homedir}/.project/logs/project.out.log`, {
    size: '50M',
    interval: '1d',
    compress: 'gzip'
});
const _err = rotatingFileStream(`${os.userInfo().homedir}/.project/logs/project.error.log`, {
    size: '50M',
    interval: '1d',
    compress: 'gzip'
});
```

**Comment by iccicci** [comment]
Try this:
`
const opt = {
    size: '50M',
    interval: '1d',
    compress: 'gzip',
    path: `${os.userInfo().homedir}/.project/logs`
}
const _out = rotatingFileStream('project.out.log', opt);
const _err = rotatingFileStream('project.error.log', opt);`

**Comment by DuanPengfei** [comment]
I have tried that options, set `path` parameter, the folder like `20170531-1617-01-` appeared in `/Users/someone/.projectName/logs`. 

```
// index.js
if(options.path) {
    var generator = this.generator;

    this.generator = function(time, index) {
        return path.join(options.path, generator(time, index));
    };
}
```
From above code, we can know if set `path` option, `this.generator` will be a function, the function return `path.join(options.path, utils.createGenerator(filename)(time, index));`

After reading source code, I think whether or not set `compress` option, the folder will always be created. Set `path` option just change the path of the folder.

**Comment by iccicci** [comment]
It looks like your _filename_ parameter is starting with a _slash_ character.

Are you sure you wrote
```
const _out = rotatingFileStream('project.out.log', opt);
```
and not
```
const _out = rotatingFileStream('/project.out.log', opt);
```
?

Thank you,
iCC

**Comment by DuanPengfei** [comment]
My `filename` is an absolute path, but this is not the key of the problem. Even if I use a `filename` like `project.out.log`, also will create file `20170602-0933-01-soul.error.log`. From the source code, we know the file will be created anyway.

**Comment by iccicci** [comment]
If your _filename_ contains a path and not just only the name of the file, this is a problem: the package is designed to accept only the name of the file in the _filename_ parameter and the _path_ in the appropriate option.

The target of this package is to create files with names similar to the one you reported after each rotation... if those files are created after rotations is just the purpose of the package, not a problem.

I don't know how to help you...
You can try to describe which is the target you are trying to reach, so I can say you if this package can help you and how....

**Comment by DuanPengfei** [comment]
👌
