### ISSUE TITLE
Intermittent activity results in data from different periods in the same time rotated file

### ISSUE THREAD

**Issue by tkurki** [iccicci/rotating-file-stream#15]
When rotating by interval filename generator is supposed to return _not-rotated file name_ when there is no time parameter initially and writing will happen to this file. 

When rotation happens filename generator is called with time parameter being the beginning of the just ended rotation interval and the _not-rotated file name_ will be moved to be named per returned value.

With `1h` rotation interval and filename generator returning `current.log` when there is no time parameter  imagine the sequence:
- start app at 12:01 => writes appended to `current.log`
- app crashes / is killed 12:59
- start app at 13:01 => writes appended to `current.log`
- rotation comes up at 14:00 => `current.log`  moved to 20170917T13 and new `current.log` created

Now `20170917T13` contains data that should have been in log file `20170917T12`.

https://gist.github.com/tkurki/3eb2fc0ce563985c57952b5a52ef5424 can demonstrate this with minute resolution.

Is there an easy way to fix things so that data would always be in a correctly timestamped file with this package or should I look elsewhere?

**Comment by iccicci** [comment]
Nope @tkurki , there is not a ready solution for this problem.

Even if I think this is a common problem for all other log rotation tools, why not cover this case as well?

A quick solution coming to my mind could be following:
at RFS init time to check the _no rotated file_ timestamp and eventually perform a rotation job if it's out of rotation interval.

Please let me know if this solutionc could be fine for U and/or if other solution come to your mind (than expose them to me).

Thank you,
iCC

P.S.
I didn't checked your demonstration: I know my package and I recognize the described behavior. If in the demo there are some other useful info, please make me aware about that.

**Comment by tkurki** [comment]
I switched to https://www.npmjs.com/package/file-timestamp-stream, which covers just this particular use case with patter based file naming.

**Comment by iccicci** [comment]
I'll implement that anyway
