### ISSUE TITLE
Initial log file

### ISSUE THREAD

**Issue by EmanuelSanchez** [iccicci/rotating-file-stream#16]
Hi, I want to use the package to create a rotating log file with time, I did it, but the first log file doesn't have the time stamp as the following. I have seen the package documentation, but I can't understand if there is this option inside the package.

This is my configuration:
![image](https://user-images.githubusercontent.com/24307567/31313533-d49ad4dc-abb3-11e7-8cba-17a813c87c31.png)

**Comment by iccicci** [comment]
Hi @EmanuelSanchez ,

no there is no way to do what you are looking for.
Anyway it sounds a bi strange, usually log systems works i the same way: the _not rotated log file_ keeps its original name till its rotated, that lets to follow logs with the simple command:

`
$ tail -F file.log
`

If _not rotated log file_ constantly changes its name, before to do a simple `tail -f` you shold check the current time...
It seems not comfortable.

Please let me what you think about.

Thank you,
iCC

**Comment by iccicci** [comment]
Closing due to lack of feedback

**Comment by iccicci** [comment]
I thought about this... if it is needed by somebody, why not to do it?

**Comment by EmanuelSanchez** [comment]
Hi Daniele!

Excuse me for not answering before.

My problem is that I was using a configuration that removes the previous log files and create new one if it had no rotated. Then I lost the log information. It because I am developing, then I was stopping and starting the node app.
Now, I found a configuration that save the log information when I restart the app, then I am using it. This is my configuration:

![image](https://user-images.githubusercontent.com/24307567/32659276-5deeaefc-c5f4-11e7-9791-7f24b6a984c4.png)

**Comment by iccicci** [comment]
Resolved with v1.3.3
