### ISSUE TITLE
the "maxFiles" options didn't work

### ISSUE THREAD

**Issue by YxxY** [iccicci/rotating-file-stream#18]
followed the given example, and I add the "maxFiles" opts to 10, but number of the rotated files still continue to rise by larger than 10, did i miss something in the doc?  hope to hear back, thanks!

**Comment by YxxY** [comment]
add some details, I tried it on windows 7 64bit, have not tried linux yet. Actually I got a history file with right 10 file names in it, it seems to be the latest files.......so is this all the 'maxFiles'  option can do and i need to the rest of the job?

**Comment by iccicci** [comment]
Hi,

no, it seems something is not working fine.
Are you using listeners for events `error` and `warning` ?

**Comment by YxxY** [comment]
@iccicci yes, I add both of the listeners, but no error or warning found.

**Comment by iccicci** [comment]
Can you paste here your code plz?

**Comment by YxxY** [comment]
my apology for not offering the code for the first time.
for I don't want to make thing complicated, so I pick up the testing code as follows
```js
function pad(num) {
    return (num > 9 ? "" : "0") + num;
}

function generator(time, index) {
    if (!time)
        return "file.log";

    var month = time.getFullYear() + "" + pad(time.getMonth() + 1);
    var day = pad(time.getDate());
    var hour = pad(time.getHours());
    var minute = pad(time.getMinutes());

    return "/" + month +
        day + "-" + hour + minute + "-" + index + "-file.log";
}


var rfs = require('rotating-file-stream');
var fp = __dirname + '/traces';
var fs = require('fs')
var log = console.log.bind(console)
var stream = rfs(generator, {
    size: '200B',
    maxFiles: 10,
    path: fp
});

stream.on('warning', function (err) {
    log(err)
});

stream.on('error', function (err) {
    log(err)
});

for (var i = 0; i < 200; i++) {
    stream.write(`hello world ${i}\n`)
}
stream.end('This is the end\n')
```
no error reported until I increase the limit value `i` to 1000.
then I got three types of errors
```js
{ Error: EPERM: operation not permitted, unlink 'D:\coding\express\traces\20171028-1450-5-file.log'
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'D:\\coding\\express\\traces\\20171028-1450-5-file.log' }
{ Error: UNKNOWN: unknown error, open 'D:\coding\express\traces\file.log.txt'
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'open',
  path: 'D:\\coding\\express\\traces\\file.log.txt' }
{ Error: ENOENT: no such file or directory, unlink 'D:\coding\express\traces\20171028-1450-31-file.log'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'D:\\coding\\express\\traces\\20171028-1450-31-file.log' }
```
have no idea about the `operation not permitted` error for I tested it on windows and 
the `unknown error` occurred occasionally during the test. eg: add a empty space at the end of `hello word`
For the last error, it's kind of wired because I can see that file it mentioned on my disk and the directory is right.
BTW, tested the same code on Ubuntu 16.04, no error, warning or other problems except still got more than 10 files.....
FYI.

**Comment by iccicci** [comment]
Hi @YxxY ,
in theory your code seems to have no problem, as you say on ubuntu there are no errors nor warnings.

Observing your code I can say that it causes several rotations per second: the main loop has no pause and rotation size is only 200 bytes...
Probably some events cross... honestly the package is not tested for such senario.

I relaxed the main loop as follows and I had no problems.
```
function write(i) {
    if(i == 2000)
        return;

    stream.write(`hello world ${i}\n`)
    setTimeout(write.bind(null, i + 1), 10)
}

write(0)
```

Please let me know what you think about

**Comment by YxxY** [comment]
thanks for your reply @iccicci 
I test your code, it works and I got the idea how to use it. but still a little confused, why the main loop just ignored the rotations event and didn't handle it in the next tick?  Does that mean the `maxFile` option is not suitable for the high concurrency situation.  I'm not sure about this theory, can you explain it a little bit, thanks in advance!

**Comment by iccicci** [comment]
More or less, yes, @YxxY 
not only the `maxFile` , but the whole package is not tested to handle high numbers of rotations in a second... it is not a real use case

**Comment by YxxY** [comment]
ok, I will do more research on it, thanks a lot!
