### ISSUE TITLE
type check error when using rfs with express, morgan and typescript

### ISSUE THREAD

**Issue by raycarter** [iccicci/rotating-file-stream#19]
I am trying to use rotating-file-stream in express with morgan. Everything is coded just as the tutorial of [morgan](https://github.com/expressjs/morgan) but got this error: Argument of type '"combined"' is not assignable to parameter of type 'FormatFn'. I load a screenshot as following.

![image](https://user-images.githubusercontent.com/2765326/32598072-0189efde-c539-11e7-9566-009e0fb4f196.png)

### Version info:
rotating-file-stream@1.3.2
express@4.16.2
@types/express@4.0.39
morgan@1.9.0
@types/morgan@1.7.35

**Comment by iccicci** [comment]
Never seen something similar.
For sure I can say that the error is not raised by this package nor the package has type checks.

**Comment by iccicci** [comment]
Sorry, but I don't know **typescript** .
What I can say for sure is that we can write `stream.write(...)` ... I don't know which kind of checks does _morgan with typescript_ .

**Comment by raycarter** [comment]
I can see the problem is that morgan requires a stream which has a `write` property defined. [type definition code](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c6835d5e1739663d0a5ef548274a54cc3bd9d069/types/morgan/index.d.ts#L127)

It could be a solution that a type difinition is added for rfs. I will try to do this.

**Comment by iccicci** [comment]
Yep, but unfortunately that does not says which low level checks are done on that property.

The stream has for sure a **write** property, maybe inherited from **stream.Writable.prototype** .

Can you try to add following line as last line of rfs constructor and give me some feedback?
```
    this.write = this.write;
```

**Comment by raycarter** [comment]
This line does the magic! Typescript complains no longer! Great, thanks very much!

**Comment by iccicci** [comment]
Resolved with v1.3.3
