### ISSUE TITLE
TypeScript Declaration

### ISSUE THREAD

**Issue by rakshith-ravi** [iccicci/rotating-file-stream#27]
Please add a index.d.ts for typescript

**Comment by iccicci** [comment]
I'm sorry, but I don't know typescript.

If you can do it by yourself, I'll be glad to support you doing it and applying your pull request.

That's all can do,
iCC

**Comment by rakshith-ravi** [comment]
Sure. No problem. I'll update the repo with a definition file.

PS. You really should check out typescript. It's beautiful

**Comment by iccicci** [comment]
I trust you!
I would like to learn everything.. but I'm afraid I have not enough time. ;)

Thank you for your cooperation!

**Comment by rakshith-ravi** [comment]
Haha I can understand. Anyways, I've created a PR for this. Could you add it and push it to NPM please?
