### ISSUE TITLE
rfs writing to the original file after rotated

### ISSUE THREAD

**Issue by CaptainObvious76** [iccicci/rotating-file-stream#32]
I have this in my code -

    // create a rotating write stream
    var accessLogStream = rfs(logFileName, {
      interval: '5m', 
      path: logDirectory
    });

The log files created every 5 minutes are -
<server> ! /tmp: ls -ltr *access*
-rw-rw-r-- 1 dev develop   0 Nov 28 09:50 20181128-0950-01-access.log
-rw-rw-r-- 1 dev develop   0 Nov 28 09:55 20181128-0955-01-access.log
-rw-rw-r-- 1 dev develop 782 Nov 28 09:58 20181128-0945-01-access.log
-rw-rw-r-- 1 dev develop   0 Nov 28 10:00 20181128-1000-01-access.log
-rw-rw-r-- 1 dev develop   0 Nov 28 10:05 20181128-1005-01-access.log
-rw-rw-r-- 1 dev develop   0 Nov 28 10:10 access.log

The original file created when the server started is access,log, which was renamed to 20181128-0945-01-access.log. The server still keeps logging to 20181128-0945-01-access.log file instead of logging it to access.log

**Comment by iccicci** [comment]
Hi @CaptainObvious76 ,

I cant reproduce the problem.
Could you please provide me a bigger piece of your code including all relevant parts (variables initialization and stream use)?

Thank you,
iCC

**Comment by CaptainObvious76** [comment]
My logger.js is as shown -


---------------------------------------------------------------
var webServerConfig = require('./web-server.js');

const { createLogger, format, transports } = require('winston')
const { colorize, combine, timestamp, printf } = format

// Define your custom format with printf.
const myFormat = printf(info => {
  return `${info.timestamp} ${info.level}: ${info.message}`
})


var options = {
  file: {
level: 'info',
    filename: webServerConfig.logfile + '/' + webServerConfig.logfilename,
    handleExceptions: true,
    maxsize: 5242880, //5MB
    maxFiles: 5,
json: true,
timestamp: true,
  },
  console: {
    level: 'debug',
    handleExceptions: true,
    json: false,
    colorize: true,
timestamp: true,
  },
};


var logger = createLogger({
format: combine(
    timestamp({
format: 'MM/DD/YYYY HH:mm:ss.SSS'
}),
    colorize(),
    myFormat
  ),
    transports: [
      new transports.File(options.file),
//      new transports.Console(options.console)
  ],
  exitOnError: false, // do not exit on handled exceptions
});

module.exports = logger;
module.exports.stream = {
    write: function(message, encoding){
        logger.info(message);
    }
};
---------------------------------------------------------------------------------------------------------------


My config/web-server.js is as shown -

-------------------------------------------------------------------------------------------------------------
const morgan          = require('morgan');
const http            = require('http');
const https           = require('https');
const express         = require('express');
const webServerConfig = require('../config/web-server.js');
const logger          = require('../config/logger.js');
const router          = require('./router.js');
const database        = require('./database.js');
const fs              = require('fs');
const path            = require('path');
const rfs             = require('rotating-file-stream');
const bodyParser = require('body-parser');

let httpsServer;

function initialize() {
  return new Promise((resolve, reject) => {
    const app = express();

// use body parser to parse json
app.use(bodyParser.json()); // support json encoded bodies
app.use(bodyParser.urlencoded({ extended: true })); // support encoded
bodies
var sslOptions = {
  key: fs.readFileSync('key.pem'),
  cert: fs.readFileSync('cert.pem'),
  passphrase: 'c3rt!23'
};

var logDirectory = webServerConfig.logfile;
var logFileName  = webServerConfig.logfilename;
// ensure log directory exists
    fs.existsSync(logDirectory) || fs.mkdirSync(logDirectory);

    // create a rotating write stream
    var accessLogStream = rfs(logFileName, {
      interval: '1d', // rotate daily
      path: logDirectory
    });

    // setup the logger
    app.use(morgan('combined', {stream: logger.stream}));
    httpsServer = https.createServer(sslOptions, app);

    // Mount the router at /jda so all its routes start with /jda
app.use('/jda', router);

    httpsServer.listen(webServerConfig.port, err => {
      if (err) {
        reject(err);
        return;
      }

  logger.info(`Web server listening on localhost:${webServerConfig.port}`);


      resolve();
    });
  });
}

module.exports.initialize = initialize;


function close() {
  return new Promise((resolve, reject) => {
    httpsServer.close((err) => {
      if (err) {
        reject(err);
        return;
      }

      resolve();
    });
  });
}

module.exports.close = close;
-------------------------------------------------------------------------------------------------------------------------------------------------------------

Thanks for the quick response.

**Comment by iccicci** [comment]
Hi @CaptainObvious76  ,

```
app.use(morgan('combined', {stream: logger.stream}));
```

you are not using **rotating-file-stream**, you are using winston...


Hope this helps,
iCC

**Comment by CaptainObvious76** [comment]
It does. Thank you!
