### ISSUE TITLE
The document for compress a log file to gz is not correct

### ISSUE THREAD

**Issue by powentan** [iccicci/rotating-file-stream#41]
Hi,

I found the example:
![image](https://user-images.githubusercontent.com/168433/62176897-9f7fa900-b375-11e9-8cc4-d6bf0c738020.png)

It works but it remains a log file without ".gz".
And I found there is a closed issue: https://github.com/iccicci/rotating-file-stream/issues/5
It suggests to do "rm -f " + dest in the compress function.
I think you can update the document to let the user do the thing right in the first place.

Best regards,
Powen

**Comment by iccicci** [comment]
Hi @powentan ,

the package should remove the original log file (the not compressed one) by itself...
I'll check deeper.

Thank you,
iCC

**Comment by iccicci** [comment]
Hi @powentan ,

is it possible that rather than the example you pasted, you used something like follows?
```
var rfs = require("rotating-file-stream");
var stream = rfs("file.log", {
    size: "10M",
    compress: function(source, dest) {
        return "cat " + source + " | gzip -c9 > " + dest + ".gz";
    }
});
```

Please note the `+ ".gz"` at the end of returned command line.

**Comment by iccicci** [comment]
Hi @powentan ,

I think the problem is that your procedure creates a file with a different name than the one passed in input to `compress` _function_ as `dest` parameter.

Anyway I'm closing this issue due to lack of feedback.

Hope this helps,
iCC
