### ISSUE TITLE
Compress gzip error

### ISSUE THREAD

**Issue by MohGanji** [iccicci/rotating-file-stream#42]
this is the configuration that I used:
```
const expressLogStream = rfs('express.log', {
  interval: '1m',
  compress: 'gzip',
  maxFiles: 100,
  path: path.join(__dirname, '..', 'public', 'logs'),
})
```

and I get this error that ends node process:

```
/Users/m0hammad/pheebs/episode-server/node_modules/rotating-file-stream/compress.js:216
        for(var i in files) files[i].once("error", callback);
                                     ^

TypeError: files[i].once is not a function
    at RotatingFileStream.gzip (/Users/m0hammad/pheebs/episode-server/node_modules/rotating-file-stream/compress.js:216:31)
    at /Users/m0hammad/pheebs/episode-server/node_modules/rotating-file-stream/compress.js:102:14
    at FSReqCallback.oncomplete (fs.js:137:23)
```

**Comment by iccicci** [comment]
Hi @MohGanji ,

first of all, have you attached an handler to `error` and `warning` events?

Something like:
```
expressLogStream.on('error', function(err) {
  console.log(err);
});
expressLogStream.on('warning', function(err) {
  console.log(err);
});
```

Please give me a feedback.

Thank you,
iCC

**Comment by MohGanji** [comment]
Thank you for responding quickly @iccicci ,
this looks like a syntax problem. As the error log says, it's a TypeError, it does not show anything in error or warning, the whole node process exits with this error.

**Comment by iccicci** [comment]
Hi @MohGanji ,

I'm afraid this is caused by a previously ignored error.
Can you please tell me precisely if you added the two handlers I suggested?

Thank you,
iCC

**Comment by MohGanji** [comment]
@iccicci yes I did add the two handlers, but I don't see any logs related to them.

**Comment by iccicci** [comment]
Ok @MohGanji ,

thank you, I'll check deeper.

**Comment by iccicci** [comment]
Hi @MohGanji ,

unfortunately I was not able to reproduce the error.
Can you please give me some details about your running environment?
OS used? Node.js version? When do you get the error: at first rotation attempt or later at a random rotation attempt?

Thank you,
iCC

**Comment by MohGanji** [comment]
@iccicci 
I'm using node v.12.3.1 on macOS mojave, and it always happens at the first rotation.
When the server crashes, there are these temp files in the destination directory:
```
express.log.0.gz
express.log.0.rfs.tmp
```

Thanks for your efforts.
Mohammad

**Comment by iccicci** [comment]
Hi @MohGanji ,

it's so strange: I more or less replicated the code in the [official example](https://nodejs.org/api/zlib.html#zlib_zlib), the only difference is that I used the `once` method rather than the `on` one to catch errors.
Before reading the edit of your last commit I would have said that I did a branch (issue42) and would have asked you to try to clone it in your working environment to check if if could solve the issue as I test the package under Ubuntu, but after reading your last comment we can already say the problem is not the OS.

I'm afraid you discovered some hidden bug, If you want to share your code with me I could try to check the package deeper and in the right context.

Hope this helps,
iCC

**Comment by MohGanji** [comment]
Hi @iccicci ,
I can't give you the source code because it's part of a big project. but I try to reproduce it with the smallest portion of code possible to be able to share it with you.
Can you send me your email address to share the code privately?

**Comment by iccicci** [comment]
@MohGanji ,

daniele dot icc at gmail dot com

Let's try to fix this!

**Comment by MohGanji** [comment]
@iccicci I started pruning the code, and I found exactly what is causing the error. I have a small piece of code that I'm not proud of, but it makes a lot of stuff easier for me.

This is the piece of code that causes rfs to crash when the compression option is used:

```
Array.prototype.insert = function(index, item) {
      this.splice(index, 0, item)
      return this
}
```

At first I thought it could be because "insert" is a commonly used name, but then I changed it to something like "insertxxxxxxx" but it still caused the code to crash. I realized changing Array prototype in any way results in this. Like for example:

```
Array.prototype['anything'] = 1
```

Please take a look at whats happening here!

**Comment by iccicci** [comment]
Hi @MohGanji ,

that's the point!

If you check the line with the error you can see I'm using an old fashion style way to iterate over an array, that combined with what you wrote originates the error!
I was already planning to change with with a `map` method, now it's time to do it; more than this I'll add the _ugly_ thing you did as another test case.
In a couple of days I would be able to release a new version of the package immune to `Array.prototype` changes.

Thank you for helping me making **rotating-file-stream** always better!

iCC

**Comment by MohGanji** [comment]
Thank you for responding quickly and trying to solve the issue.
please inform me when it's done and close the issue then.

Mohmmad.
