### ISSUE TITLE
Compression does not create .gz file

### ISSUE THREAD

**Issue by MohGanji** [iccicci/rotating-file-stream#43]
Hi, 

like there is another issue now, I only added the compression option, and there resulting rotated files are some kind of binary files that I could not figure out how to see their content. they cannot be decompressed with gzip, and mac finder cannot open them, they don't have .gz suffix either.

**Comment by iccicci** [comment]
Hi @MohGanji :)

I need some more details in order to investigate.

Thank you,
iCC

**Comment by MohGanji** [comment]
Well, Consider the previous setup from issue #42 ,
I added `compress: 'gzip'` option to it, now the files created are some binary files like this:

> 20191002-0820-01-express.log

I assumed that the result is supposed to be a file with `.gz` suffix.

UPDATE: I added `.gz` to these files manually and I can decompress them successfully.

**Comment by iccicci** [comment]
Hi @MohGanji ,

if I understood correctly, everything is working fine except for the rotated compressed file.
If that's true, the package offers the possibility to _play_ with filenames using the [filename generator function](https://www.npmjs.com/package/rotating-file-stream#function-filenametime-index).

Hope this helps,
iCC

**Comment by MohGanji** [comment]
Thanks, that works.
