### ISSUE TITLE
Version 2.x seems incompatible with Hapi's good plugin

### ISSUE THREAD

**Issue by stefcameron** [iccicci/rotating-file-stream#48]
Hello! 👋 Thanks for making this great module. It's really useful.

I was happily using the 1.x version of this module with the Hapi framework's https://hapi.dev/family/good/api/?v=9.0.0 plugin. Basically, that boils down to:
```javascript
{
  module: 'rotating-file-system',
  args: [
    'filename'
    {
      ...options...
    }
  ]
}
```
in the plugin's configuration. Setting 'module' to a string which is a package name results in the plugin requiring the package _and assuming the default export is a constructor_ it will call `new` on in order to get a new `stream.Writable` instance. This worked well with version 1.x...

With version 2.x, however, it's broken:
1. The default export isn't the class anymore.
2. While the class itself is exported, and could be provided as the `module` option in the plugin's config, the class now requires a "generator" function as its first parameter instead of a file name string.
3. Looking inside the `rotating-file-stream` package, passing a string as the `filename` parameter to the also-exported `createStream()` function internally calls `createGenerator()` (because I don't set the `rotate` option to non-zero), but `createGenerator()` isn't exported, so must be copied.

If I copy `createGenerator()`, then I can do this to get things working again:
```javascript
const rfs = require('rotating-file-stream');

const createGenerator = function(filename) {
  // ...verbatim from rotating-file-stream... //
}

class RotatingFileStream extends rfs.RotatingFileStream {
  constructor(filename, options) {
    super(createGenerator(filename), options);
  }
}
...
// plugin config
{
  module: RotatingFileStream,
  args: [...]
}
```
But the problem with that is that it circumvents the call to the also-internal `checkOpts()` method that massages the given `options` object before passing it to the `RotatingFileStream` constructor internally. So I'd have to copy that out as well to be really "complete", but that's now getting into internal logic, which is even messier.

What I would propose, to stay as much as possible inline with the direction this module took in 2.x and yet remain backward-compatible here, is:
1. Expose `createGenerator()` as a utility to create a default generator to pass to the constructor (could also point this out in the README where the "complex generator function" example is given, since this is the same implementation).
2. Move the call to `checkOpts()` out of `createStream()` and into the `RotatingFileStream` constructor since `createStream()` doesn't even use that function's output (it just passes it to the constructor and instead still uses the original `options.rotate`).

**Comment by iccicci** [comment]
Hi @stefcameron ,

if I understood correctly, by chance, v1 interface of RotatingFileStream was compliant with Hapi and this is no longer true with v2.

The keyword is: _by chance_.

In my opinion the best way to solve this problem is to write a dedicated package, something which has an interface respecting Hapi specification and using RotatingFileStream in the deep.
By this way, this new package will be the responsible to keep compliance between the two distinct SW and I'll not have to keep RotatingFileStream compliant with something not related to it (Hapi in this case).

What do you think about?

Thank you,
iCC

**Comment by stefcameron** [comment]
@iccicci Thanks for getting back to me and for your thoughts on this. Yes, you're correct, it's _by chance_ that your package was working with `@hapi/good`'s interface. If you're not interested to remain compatible with it, which is understandable, that's certainly your decision to make. I realize you didn't set out to support this when you first created this module. 🙂 

Creating a new package that's meant to be used with Hapi is an alternative, but it seems a little heavy-handed -- perhaps because I don't have as much context into the decision to hide the class and expose a function to instantiate the class instead in your 2.x release.

I guess such a package would create its own class extending a writable stream (what `@hapi/good` expects), create an internal instance of `RotatingFileStream` via `createStream()`, and then just act as a proxy for all writable stream calls into that internal instance.

I did ponder this a bit more and realized I could do what follows, which still feels hacky, but is at least cleaner than pulling pieces of code out of your module to fill-in the gaps:

```javascript
const rfs = require('rotating-file-stream');

class RotatingFileStream extends rfs.RotatingFileStream {
  constructor(filename, options) {
    return rfs.createStream(filename, options);
  }
}
```

(I guess you could also argue that `@hapi/good`'s interface requiring a constructor function isn't the greatest either. 😉 )

**Comment by iccicci** [comment]
Hi @stefcameron ,

reading your feedback I think this issue could closed. Do you agree?

Thank you,
iCC

**Comment by stefcameron** [comment]
Yes, @iccicci, the issue can be closed. Thanks for your time.
