### ISSUE TITLE
Compress with .gz extention

### ISSUE THREAD

**Issue by alainm** [iccicci/rotating-file-stream#5]
I am trying to use rotating-file-stream with Hapi.js and good.

My trouble is that the compresses files don't have a **.gz extention** and that makes most Linux utilities confuzed.
If I change the compress string to add '.gz', the file with the same name is not deleted but it's size is set to zero !!! I expected the file to be deleted. 
BTW: the docs say not to delete source file, I tried it and strage errors happen (as expected)

This is the relevant part of my setup:

``` javascript
      {
        module: 'rotating-file-stream',
        args: [
          'nodejs-web.log',
          {
            path: './logs',
            size: '10K',
            interval: '1m',
            compress: function( source, dest) {
              return 'cat ' + source + ' | gzip -c9 > ' + dest + '.gz';
            }
          }
        ]
      }
```

This is what I get:

```
ls -l
-rw-rw-r-- 1 user user 1347 Jul 22 20:32 20160722-2032-01-nodejs-web.log.gz
-rw-rw-r-- 1 user user    0 Jul 22 20:44 20160722-2043-01-nodejs-web.log
-rw-rw-r-- 1 user user 1207 Jul 22 20:44 20160722-2043-01-nodejs-web.log.gz
-rw-rw-r-- 1 user user    0 Jul 22 20:44 20160722-2044-01-nodejs-web.log
-rw-rw-r-- 1 user user 1263 Jul 22 20:44 20160722-2044-01-nodejs-web.log.gz
-rw-rw-r-- 1 user user 7107 Jul 22 20:44 nodejs-web.log
```

**Comment by alainm** [comment]
Hi, I found a way to solve this...
I Modified the compress function like this:
(I am also deleting files with more then 30 days)
``` javascript
            compress: function (source, dest) { // Modified compress function, add extension .gz
                                                // Also removes logs older than 30 days
              return 'cat ' + source + ' | gzip -c9 > ' + dest + '.gz; rm -f ' + dest +
                     '; find ./logs/* -mtime +30 -delete';
            }
 ```
I am leaving this open for anyone to tell a better way to add the .gz extension

**Comment by iccicci** [comment]
Have you tried to use a different _file name generator function_ ?

The way to change file names is to use an appropriate _generator_ .
https://github.com/iccicci/rotating-file-stream#function-filenametime-index

**Comment by iccicci** [comment]
Closing due to lack of feedback

**Comment by ChristopherWilcoxen** [comment]
Since it took me a while to understand what iccicci meant by "Have you tried to use a different file name generator function?", I just wanted to elaborate and say he means if you're using compression and want the extension, add ".gz" to your returned file name in the generator function.
