### ISSUE TITLE
How to fix the unhandled exceptions like permission issue return from rfs

### ISSUE THREAD

**Issue by slashd0t** [iccicci/rotating-file-stream#50]
Hi guys @jorgemsrs @iccicci
I just found an issue in which if the log file don't have a write permission. 
The error will occur if the log file is read-only that was modified by an another node app or intentionally change the file permission.

It will return a TypeError like this which is confusing to the end-user:
```
node app.js
Express server listening on port 3333
TypeError: this.destroy is not a function
    at destroy (/home/armano/_node/webinnov_project/node_modules/rotating-file-stream/index.js:71:18)
    at rewrite (/home/armano/_node/webinnov_project/node_modules/rotating-file-stream/index.js:78:24)
    at fsStat (/home/armano/_node/webinnov_project/node_modules/rotating-file-stream/index.js:102:28)
    at FSReqWrap.oncomplete (fs.js:111:15)

```
To solve this TypeError I have modified the destroy() function to put in a try-catch. For example:
```
  private rewrite(chunk: Chunk, callback: Callback): void {
    const destroy = (error: Error): void => {
      try {
        this.destroy();
      } catch(error) {
        return callback(error);
      }
    };
...
...
```
Here's my snippets using the rfs:
```
this._debuggerStream = rfs.createStream("debug.log", {
  size: '50M',
  interval: '1d',
  immutable: true,
  path: this._directory,
  mode: 0o777
})

// Since we have the try-catch, the exception will now catch here instead of displaying
// TypeError: this.destroy is not a function --which is confusing to the end-user
this._debuggerStream.on('error', function (err) {
  console.log('MyWebApp Debug Error - %s', err)
})
```

What do you think of my fix? Or do you have idea on how to catch the rfs exception in onError event? Your help will be greatly appreciated.
Thanks!

**Comment by iccicci** [comment]
Hi @slashd0t ,

did U closed the pull #49 because you think the message is confusing and you think a different approach could be better?

**Comment by slashd0t** [comment]
Hi @iccicci, yeah I closed my Pr. What I did is I put a try-catch in the destroy() whenever there is an exception to catch and it will handle by using onError event in rfs.

```private rewrite(chunk: Chunk, callback: Callback): void {
    const destroy = (error: Error): void => {
      try {
        this.destroy();
      } catch(error) {
        return callback(error);
      }
    };```
I'm not sure if this is a good approach.

**Comment by iccicci** [comment]
Thank you @slashd0t ,

can you be more specific when you speak about changing file permissions?
Which kind of change do you speak about?
When do you receive the exception? At a new rotation job? At a new write call? At some other time?

Thank you

**Comment by iccicci** [comment]
Hi @slashd0t ,

I noticed something really strange: the [destroy](https://nodejs.org/api/stream.html#stream_writable_destroy_error) method is a _native method_ for _Stream class_: are you sure you never overwrite the `destroy` attribute of the **RotatingFileStream** object?

Thank you,
iCC

**Comment by slashd0t** [comment]
_Can you be more specific when you speak about changing file permissions?_
- My node app will generate lots of log files but I've another monitoring app that will read the log file and set a read-only file temporarily and process them. However, the rfs can no longer read the log files and it suddenly terminate my app.
I'm expecting that whenever there's an rfs exception it will catch but the onError didn't catch the exceptions. For example:
```
this.rfsStream.on('error', function (err) {
  console.log('Log Debug Error - %s', err)
})
```

_Which kind of change do you speak about?_ 
- We just need to add try-catch in the destroy() so that if there is an exception it will be catch through Error event.

_When do you receive the exception? At a new rotation job? At a new write call? At some other time?_
- I got the exception after 5 minutes on the next write call.

Yeah, I just added a try-catch:
See below the existing typescript code:
**Before:**
```
private rewrite(chunk: Chunk, callback: Callback): void {
  const destroy = (error: Error): void => {
    this.destroy();
    return callback(error);
  };
  ...
  ...
```


**After:**
```
private rewrite(chunk: Chunk, callback: Callback): void {
  const destroy = (error: Error): void => {
    try {
      this.destroy();
    } catch(error) {
      return callback(error);
    }
  };
  ...
  ...
```

**Comment by iccicci** [comment]
Hi @slashd0t ,

I'm sorry but I was not able to reproduce the error, I tried with `chmod 0` but nothing...
I need some more detail to reproduce the error.

More than this I repeat my previous question:
the [destroy](https://nodejs.org/api/stream.html#stream_writable_destroy_error) method is a _native method_ for _Stream class_: are you sure you never overwrite the `destroy` attribute of the **RotatingFileStream** object?

Thank you,
iCC

**Comment by slashd0t** [comment]
Hi iCC, this is what I did, so in my express app(app.js) I have this rotating file stream instance where I logged some data:
```
this._debuggerStream = rfs.createStream("debug.log", {
  size: '1K',
  interval: '1d',
  immutable: true,
  path: this._directory,
  mode: 0o777
})
```
But before I start: **npm start** I've chmod the debug.log file first. Example: **chmod 0 debug.log**
So once I start the express app, I got this error message:
```
Express server listening on port 3000
TypeError: this.destroy is not a function
    at destroy (/home/armano/_node/webinnov_project/node_modules/rotating-file-stream/index.js:71:18)
    at rewrite (/home/armano/_node/webinnov_project/node_modules/rotating-file-stream/index.js:78:24)
    at fsStat (/home/armano/_node/webinnov_project/node_modules/rotating-file-stream/index.js:102:28)
    at FSReqWrap.oncomplete (fs.js:111:15)

```

Regarding the destroy() I'm referring to this line:
https://github.com/iccicci/rotating-file-stream/blob/master/index.ts#L163

**Comment by iccicci** [comment]
Hi @slashd0t ,

I added a test case to cover the described scenario and I correctly get a `EACCES` error on the `"error"` event handler (immediately after first write call, before the write call itself is executed). I'm still not able to replicate the problem.

Looking at the stack trace you copied, the `this.destroy` method at line 71 of rotating-file-stream/index.js file is a _Stream class_ native method; as if somewhere in your code there was something like:

```
this._debuggerStream.destroy = 42;
```

Could you check please?

Thank you,
iCC

**Comment by slashd0t** [comment]
Hi iCC,
I just review my code but I don't have this line of code `this._debuggerStream.destroy = 42;`
What's does 42 means?

Yeah, this.destroy() is a Stream class method. So I cannot changed that, I only added a try-catch in the destroy() of rotating-file-stream class. Here's the existing destroy function:
```
const destroy = (error) => {
  this.destroy();
  return callback(error);
};

```
Thanks

**Comment by iccicci** [comment]
Hi @slashd0t ,

42 is just a value...
A native method can be changed or at least overwritten.

Due I'm not able to reproduce the problem, could you help me?
Could you please add some `console.log` to `destroy` function at line 70 of /home/armano/_node/webinnov_project/node_modules/rotating-file-stream/index.js as follows and cut&paste here the output?

```
const destroy = (error) => {
  console.log(this instanceof RotatingFileStream);
  console.log(stream_1.Writable.prototype.destroy);
  console.log(RotatingFileStream.prototype.destroy);
  console.log(this.destroy);
  this.destroy();
  return callback(error);
};
```

Thank you,
iCC

**Comment by slashd0t** [comment]
Hi iCC,
I just start my node app and log the values. See below the outputs:
$ npm start

```
> application-name@0.0.1 start /home/armano/_node/webinnov_project
> node app.js
Express server listening on port 3333
true
undefined
undefined
undefined
TypeError: this.destroy is not a function
    at destroy (/home/armano/_node/webinnov_project/node_modules/rotating-file-stream/index.js:77:18)
...
...
...
```
Hope it helps.

**Comment by iccicci** [comment]
Hi @slashd0t ,

he correct output should be:
```
true
[Function: destroy]
[Function: destroy]
[Function: destroy]
```

it seem something in your environment is removing the `destroy `attribute to `stream.Writable` class;
something like:
```
stream.Writable.prototype.destroy = undefined;
// or
delete stream.Writable.prototype.destroy;
```

This doesn't mean is done actually in your own code, but could be done in some of the package your app includes.

To identify which call does it, you can set a lot of debugging `console.log(stream.Writable.prototype.destroy)` from the first line of your app, and to check when the output stops to be `[Function: destroy]`.

Hope this helps,
iCC

**Comment by slashd0t** [comment]
Hi iCC,
I couldn't find anywhere in my node project that remove the "destroy" attribute.
Also in my installed packages I couldn't find that it remove/delete the destroy attribute.
Have you try to run a express3 app that is using rfs ?
Before you start, you should change the file permission of the log file in your terminal. 
```
armano@ubuntu /opt > $ chmod 0 debug.log
```
I expect that you will get the TypeError this.destroy is not a function.
Anyway thanks for the help.

**Comment by iccicci** [comment]
Hi @slashd0t ,

I added a test case (see two days ago commit) to cover the scenario and I correctly got an `EACCES` error in `"error"` event handler.

More than this, both the exception you get (see the stack trace you pasted) and the `console.log` output I asked you, strongly suggest the problem is the lack of `destroy` method from `stream.Writable` class; this could be because it was somehow removed or because you are using a very old **Node.js** version, earlier than v8.0.0 (as `destroy` method was introduced in that version).

If you are using a so old **Node.js** version, you simply need to upgrade it, as versions early than v10.0.0 are now deprecated ([check here](https://github.com/nodejs/Release#readme)).

If you are using a recent **Node.js** version, please add following lines at very beginning of your app (i.e. before any other `require` or `import` statement) and please tell me the output:

```
const stream = require("stream");
console.log("destroy:", stream.Writable.prototype.destroy);
```

Thank you,
iCC

**Comment by slashd0t** [comment]
Hi iCC,
Thanks for letting me know about the Node.js version. Yeah, i'm using the old version. I'll try to test again using the latest version and see if it works. Thanks.

**Comment by iccicci** [comment]
You are welcome, @slashd0t 

Please keep me update to help you solve your problem.

Thank you,
iCC

**Comment by iccicci** [comment]
Hi @slashd0t ,

any news about your problem?

Thank you,
iCC

**Comment by iccicci** [comment]
Hi @slashd0t ,

any news about your problem?

Thank you,
iCC

**Comment by slashd0t** [comment]
Hi iCC,
Yeah, I tried to update my node version to higher version(13.9) and no more _**TypeError**_ occured. But the problem here since the file was changed mode to 0(_$ chmod 0 debug.log_) so the rfs still cannot write to that file. Although there is no error been displayed in stdout and the clients app may think that it write the logs successfully but the fact it wasn't.

So any idea how the rfs handle this unhandled exception if using the lower node version(7.x) ?

Thanks.

**Comment by iccicci** [comment]
Hi @slashd0t ,

**RotatingFileStream** requires at least Node.js v10, please check the [documentation](https://www.npmjs.com/package/rotating-file-stream#compatibility).

About the RO problem... being not able to write in a file with mode 0 is the expected behavior...
I think you need to fix your log handling external app, I know several tools that elaborates logs (first of all logstash and filebeat), but this is the first time I hear about changing the mode to 0.

Hope this helps,
iCC

**Comment by slashd0t** [comment]
Hi iCCC,
Regarding the **chmod 0**. Actually, it was just an example wherein the file permission had been change and the file is not writable. That's where the rotating-file-stream(rfs) issue will occur if the file have been change the file permission. The rfs won't return an exception supposed to be it should have return an exception. Yeah, i'm familiar with logstash and filebeat that is too much for the simple app. I just want to use a simple log file with rfs.

**Comment by iccicci** [comment]
Hi @slashd0t ,

if the file permissions change and the process have no longer write access to the file, rfs should fire a EACCES error event; I added a test case and it works as expected.
Which  behavior do you expect from rfs when no write access is longer grated to the log file?

Thank you,
iCC

**Comment by iccicci** [comment]
Closing due to lack of feedback
