### ISSUE TITLE
tee functionality?

### ISSUE THREAD

**Issue by jbcpollak** [iccicci/rotating-file-stream#53]
For debugging I'd like to be able to tee output to stdout and to file. Is that possible?

**Comment by iccicci** [comment]
Hi @jbcpollak ,

yes, I think it's possible.

I think I'm going to add an option (something like `teeToStdout`) to write file content to `stdout` as well.
If you need to debug info about events, I think to leave this to you: you should need to attach an handler to the event you are interested in, which simply logs the event itself.

Do you think this can satisfy your request?

Thank you,
iCC

**Comment by iccicci** [comment]
Hi @jbcpollak ,

I had the time to do it, I just released v2.1.0 which should achieve your request.
Please comment with your feedback and/or close the issue if you think that's enough.

Thank you,
iCC

**Comment by iccicci** [comment]
Closed due to lack of feedback
