### ISSUE TITLE
v2.x: "touch" before rename breaks compatibility with certain consumers of rotated log files

### ISSUE THREAD

**Issue by macinjosh32** [iccicci/rotating-file-stream#60]
We have an Apache Flume instance set up to poll the directory containing rotated files once per second and grab/process any new files that appear.

Under RFS v1.x, this setup worked perfectly fine.

RFS 2.x appears to create an empty file at the intended destination prior to moving the actual unrotated file to that destination. Due to this change, we sometimes encounter a race condition in which Apache Flume grabs/processes the empty file instead of the rotated one. Flume then ignores the rotated file because it thinks it's already processed that file (due to its name being identical), and the rotated file never gets processed.

Is there any way under RFS v2.x to force the v1.x behavior of transferring each file to its rotated destination atomically?

**Comment by iccicci** [comment]
Short answer: no, sorry.

Now I'm at my job (I follow this project on my free time); please wait some hours for the detailed answer.

**Comment by iccicci** [comment]
Sorry for my late reply @macinjosh32 ,

the new touch was added in v2.x to cover some edge cases: if the touch fails, some actions can be taken (last change, exiting with an error), and this behavior is not configurable.

Reading at your problem I would try to sole it acting on Flume (which I don't know), if it is possible to configure it to consider a file as new not only on the name, but on size and/or timestamp as well, probably could be enough to solve your problem.

Another option could be to listen for the `rotated` event of RFS and move (or copy, depending on your needs) the newly rotated file to another directory and to configure Flume to check for files in this new directory.

Please let me know if this helped.

Thank you,
iCC

**Comment by iccicci** [comment]
Closing due to lack of feedback
