### ISSUE TITLE
Module does not emit open error without writing.

### ISSUE THREAD

**Issue by Raynos** [iccicci/rotating-file-stream#62]
I noticed that when I create a rotating file stream on a readonly file system it will fail and assign `this.error`.

The error from `this.error` is only used to destroy the stream on the first write. This leads to the following code hanging indefinitely

```js
    return new Promise((resolve) => {
      self._stream = rfs.createStream(
        self._logFileLocation,
        {
          size: MAX_LOG_FILE_SIZE,
          maxFiles: MAX_LOG_FILES,
          compress: 'gzip'
        }
      )
      self._stream.once('open', onOpen)
      self._stream.once('error', onError)

      function onOpen () {
        self._stream.removeListener('error', onError)

        self.hasOpened = true
        resolve({})
      }

      /** @param {Error} err */
      function onError (err) {
        self._stream.removeListener('open', onOpen)

        resolve({ err: err })
      }
    })
```

I believe a reasonable fix for this would be to emit an error event from the `init()` callback so that the user gets feedback about the stream without having to `write()` to it.

**Comment by iccicci** [comment]
I'll check this.

**Comment by Raynos** [comment]
I'm working on a pull request at the moment. just getting tests to pass.
