### ISSUE TITLE
Tried to run the tests locally on node 14 and they failed.

### ISSUE THREAD

**Issue by Raynos** [iccicci/rotating-file-stream#63]
I switched down from node 14 to node 12 and all the tests pass.

Something about the order and frequency of events in node14 as well as the string constants in error messages causes the entire test suite to fail.

**Comment by iccicci** [comment]
OMG!
This needs to be fixed ASAP!

Thank you

**Comment by iccicci** [comment]
It seems many changes have been applied to streams between Node.js v12 and v14; this may takes a long time

**Comment by iccicci** [comment]
It seems the fix attempt actually fixed.
