### ISSUE TITLE
rotating-file-stream with pino logger overrides the logs

### ISSUE THREAD

**Issue by felixmosh** [iccicci/rotating-file-stream#68]
First of all thank you for this awesome lib 🙏🏼

I'm experiencing some weird issue with disappearing logs.
This is my production config of `pino` logger.

```js
import path from 'path';
import pino from 'pino';
import { createStream } from 'rotating-file-stream';

function getISODate(date) {
  const clone = new Date(date);
  clone.setHours(12);
  return clone.toISOString().split('T').shift();
}

const generator = (time) => {
  if (!time) return `${filename}.log`;

  return `${filename}-${getISODate(time)}.log`;
};

const stream = createStream(generator, {
  interval: '1d', // rotate daily
  path: path.join(process.env.DEPLOY_BASE_PATH, `/logs/${filename}/`),
});

const logger = pino({ ...defaultConfig, name: filename }, stream);
```

If I check log in real time, I can see the logs without any issue. but if I check the log from "yesterday" (by the date) i see only last operation that occurred via cronjob at 23:30, rest of the day logs are not there.

I suspect that it is somehow related to my config of `rotating-file-stream`, but I don't see misconfiguration. 
Maybe you can spot the issue?

My app runs on Node v12

**Comment by iccicci** [comment]
Hi @felixmosh ,

I can see no problem in configuration of rotating-file-stream.
I admit I don't know pino, but takeing quick look to its documentation it seems you one is a correct use of both the libraries.

You are speaking about a cron job... but I have no details about it, so it's hard to say how it could impact on the logs.

What I can say, logging with two programs simultaneously (a deamon and a cron job) on the same file is not a good idea; I would suggest to use two distinct files: one for daemon's logs the other for the cron job's logs.

Hope this helps,
iCC

**Comment by felixmosh** [comment]
No, the only thing that logs is my API server. 
It got calls during the day from users, and at 23:30 each day from some cron job (via http).

During the day i do see logs of the users, but at day after that, I do see a file like "logs-2021-02-21.log" which contains only the logs of the requests that came from the cronjob... (= missing the logs of the users)

**Comment by iccicci** [comment]
I'm sorry but your report is a bit too vague.. I should know more about your cron job dedicated handlers..

In order to debug you could try  to disable the cron job to check the difference and/or attach some listener to the ratting-file-stream events.

Hope this helps.

**Comment by felixmosh** [comment]
I think that you've gave me a direction to explorer.

I have 2 sources that writes to the same log file! 
So this is not related to your lib, thank you 🙏🏼
