### ISSUE TITLE
Change file extension to .gz after compression

### ISSUE THREAD

**Issue by Shogobg** [iccicci/rotating-file-stream#69]
Hello, thank you for this package.

I noticed that the files stay with .log extension after compression.
It would be nice to have the option to change the file extension to .gz after compression, so it's more clear that this is a gzipped file.

**Comment by iccicci** [comment]
Hi @Shogobg ,

have you tried playing with the [file name generator function](https://www.npmjs.com/package/rotating-file-stream#filenametime-index) ?

Please let me know if it is enough.

Thank you,
iCC

**Comment by Shogobg** [comment]
Hello.

Somehow I've missed this part of the documentation.
Thank you very much for pointing it out!

Cheers.
