### ISSUE TITLE
Using generator with `rotate` option does not rotate the file

### ISSUE THREAD

**Issue by edrich-xendit** [iccicci/rotating-file-stream#70]
I want to use the `generator` along with the rotate option. Using the normal file name without the generator function, it works perfectly.

I have the following code:
```
const pad = num => (num > 9 ? '' : '0') + num;
const fileNameGenerator = (time, index) => {
  if (!time) return `app.log`;

  var month = time.getFullYear() + "" + pad(time.getMonth() + 1);
  var day = pad(time.getDate());
  var hour = pad(time.getHours());

  return `app.log.${month}-${day}-${hour}.${index}`;
};

logStream = createStream(fileNameGenerator, {
    path: '/var/log/app',
    interval: '10s',
    rotate: 7 // keep 7 rotated logs
  });
```

**Expected behavior:**
This should generate 7 rotated log files in 10 second intervals with the file name `app.log.${month}-${day}-${hour}.${index}`

**Observed behavior**
Only `app.log` is generated and stops logging after 10 seconds

**Comment by edrich-xendit** [comment]
Update: took a look at the source code. Can we update the readme to show that the generator function only accepts `index` param if `rotate` is specified?

**Comment by iccicci** [comment]
HI @edrich-xendit ,

https://www.npmjs.com/package/rotating-file-stream#filenameindex

It is written. Once said that, could you please update your reported code and check if the problem is still alive?

Thank you

**Comment by edrich-xendit** [comment]
Ahh, missed that. Works great now
