### ISSUE TITLE
Log rotation and generator option not working

### ISSUE THREAD

**Issue by rajasekar-mu** [iccicci/rotating-file-stream#71]
I have tried below log rotation options and used with generator on 30 mins interval. But logs created at file.log.

const pad = num => (num > 9 ? "" : "0") + num;
const generator = (time, index) => {
  _if (!time) return "file.log";_

  var month = time.getFullYear() + "" + pad(time.getMonth() + 1);
  var day = pad(time.getDate());
  var hour = pad(time.getHours());
  var minute = pad(time.getMinutes());
  return `${month}/${month}${day}-${hour}${minute}-${index}-file.log`;
};

const accessLogStream = rfs.createStream(generator, {
  size: "10M",
  interval: "30m",
  path: path.join(__dirname, 'public'),
  rotate:Math.floor(new Date().getTime() / 1000)
});
app.use(logger('combined', { stream: accessLogStream }))

Please suggest anything want to change above config.

Thanks

**Comment by iccicci** [comment]
I suggest to not use the `rotate` option.
Please let me know if this helps.

**Comment by rajasekar-mu** [comment]
@iccicci Thanks your response, now rotating
