### ISSUE TITLE
How to undo the operation of changing default shell for npm on windows 10 ?

### ISSUE THREAD

**Issue by vipulwairagade** [iccicci/rotating-file-stream#72]
I read this in docs : 

To work with the package under Windows, be sure to configure bash.exe as your script-shell.

`> npm config set script-shell bash.exe`

I executed it without thinking, now I want to undo that operation and get back to whatever original shell is used because it's breaking my other things. How do I do that ?

Please help. Thanks in advance.

**Comment by tlm-daniele-ricci** [comment]
I'm sorry @vipulwairagade , but I don't know the answer to your question.

I'm not a windows expert, sorry.
I think the answer to your question could be found in the npm itself documentation.

**Comment by iccicci** [comment]
I'm sorry @vipulwairagade , but I don't know the answer to your question.

I'm not a windows expert, sorry.
I think the answer to your question could be found in the npm itself documentation.
