### ISSUE TITLE
Compressed rotated files don't have the `.gz` suffix

### ISSUE THREAD

**Issue by Skywalker13** [iccicci/rotating-file-stream#73]
Hello, it's the intended behaviour? Looks "strange" and unusual according to **logrotate**

Thanks  
Regards

**Comment by devilmark84** [comment]
I expects too the package add `.gz` suffix.

**Comment by iccicci** [comment]
I understand... but changing the package as requested would be a breaking change...

To try to answer directly to @Skywalker13 questions: this is just something I didn't thought when I wrote the package.

Taking in account that achieving the required result (a fixed file suffix not generated by the package) with a simple [rotated file name generator](https://www.npmjs.com/package/rotating-file-stream#filenametime-index) should be quite easy, at the moment I would prefer to not apply the requested change.

Please try to apologize my (non-irrevocable) decision.

Thank you,
iCC

**Comment by iccicci** [comment]
Released v3.0.0, now the `.gz` suffix is added.
