### ISSUE TITLE
 no such file or directory, rename log failed

### ISSUE THREAD

**Issue by BARMPlus** [iccicci/rotating-file-stream#78]
When I adjust the `interval` value to a small value, it is easy to get the following error: 

**Error: ENOENT: no such file or directory，rename xxx/logs/web.log->  xxx/logs/history/20211223-5-web.log**

Version：
**node:16.13.0**
**rotting-file-stream: 3.0.2** 

This is my code：
```javascript
 const generator = (time,index) => {
    const name = 'web.log'
    if (!time) return name
    const pad = num => (num > 9 ? '' : '0') + num
    const month = time.getFullYear() + '' + pad(time.getMonth() + 1)
    const day = pad(time.getDate())
    return `history/${month}${day}-${index}-${name}`
  }

  const options = {
      maxFiles:7,
      interval:'20s',
      path: path.resolve(process.cwd(), dir)
  }

  createStream(generator, options)
```
It looks like the file is not found when renaming。
This is an occasional problem. When I request access to the log when I am about to rename the log, it is easy to get the above error.

**Comment by BARMPlus** [comment]
@iccicci need your help

**Comment by iccicci** [comment]
Hi @BARMPlus ,

I run this and I got no errors.

```javascript
const path = require("path");
const { createStream } = require("rotating-file-stream");

const dir = "test";

const generator = (time, index) => {
  const name = "web.log";
  if(! time) return name;
  const pad = num => (num > 9 ? "" : "0") + num;
  const month = time.getFullYear() + "" + pad(time.getMonth() + 1);
  const day = pad(time.getDate());
  return `history/${month}${day}-${index}-${name}`;
};

const options = {
  maxFiles: 7,
  interval: "2s",
  path:     path.resolve(process.cwd(), dir)
};

const stream = createStream(generator, options);

setTimeout(() => {}, 600000);

let count = 0;

function write() {
  stream.write(`write ${++count}\n`);
  setTimeout(write, Math.random() * 10).unref();
}

write();
```

I'm sorry but I didn't got the point when you say:

> When I request access to the log when I am about to rename the log, it is easy to get the above error.

If you meant you want to access the log file you are writing you might consider the [immutable](https://www.npmjs.com/package/rotating-file-stream#immutable) options or the [rotation](https://www.npmjs.com/package/rotating-file-stream#event-rotation) and [rotated](https://www.npmjs.com/package/rotating-file-stream#event-rotated) events: you may stop trying to access the log file between a `rotation` and a `rotated` events.

**Comment by BARMPlus** [comment]
Thank you, it's my problem, it has been solved

**Comment by zhongshanxian** [comment]
I got save error, how do you resolve ?
