### ISSUE TITLE
Not able to compress log file

### ISSUE THREAD

**Issue by ankit131996** [iccicci/rotating-file-stream#83]
I am not able to compress the log file. I want to rotate the file on the basis of size then compress the logs and save them to the desired path. Currently, I am able to save the log files (in readable form) on the basis of size without compression. 
I am using node version - v14.0.0, 
OS - Ubuntu
Code : 
const rfs = require("rotating-file-stream");
const stream = rfs.createStream(log_file_name, {
  size: "80K", // rotate every 10 MegaBytes written
  interval: "5m", // rotate daily
  //compress: true, // compress rotated files
compress: "gzip", // compress rotated files
  path: './'
});
process.stdout.write = process.stderr.write = stream.write.bind(stream);

After using the above code with compression I got a log file in this format. (File attach with this comment
[log_file.log](https://github.com/iccicci/rotating-file-stream/files/8888769/log_file.log)
)

**Comment by iccicci** [comment]
Sorry @ankit131996 ... that is a gzip file; which is the problem?

**Comment by ankit131996** [comment]
if log_file.log gzip file. how to unzip these logs? @iccicci

**Comment by ankit131996** [comment]
@iccicci  I got it. I have to add an extension in the custom file name.
