### ISSUE TITLE
Rotating log file with size, maxFiles and path options

### ISSUE THREAD

**Issue by painkkiller** [iccicci/rotating-file-stream#86]
In my app path to logs is set by the kibernetes option and looks like `path: '/opt/app/logs/backend.log'`. I have the requirement to rotate the log file, the file should not exceed 20 Mb, and only one file should be kept. So I am splitting this path with code:
```
const path = require('path');

  const fileName = path.basename(process.env.log_file);
  const logPath = path.dirname(process.env.log_file);
```
and create a rotating file stream with these options:
```
 const stream = rfs.createStream(fileName, {
                size: "20M", // rotate every 20 MegaBytes written
                maxFiles: 1, // only 1 rotated file is allowed
                path: logPath
            });
```

And I found that in this case rotation doesn't work. During the test, I am getting a lot of files with names 
![image](https://user-images.githubusercontent.com/5506725/206118106-f4ece3e5-0ac4-4712-97a2-e6cf59f6f82b.png)

**Comment by iccicci** [comment]
Hi @painkkiller ;

as far as I remember `maxFiles: 1` means **no rotated file**; i.e. the _not rotated file_ is taken in account for `maxFiles`.
Could you please try with `maxFiles: 2` to check if that fixes your problem and give me some feedback?

Once said that, I'll check (and eventually fix) this anyway in the next days.

Thank you

**Comment by painkkiller** [comment]
@iccicci thanks for very quick reply, I'll try it today. But the option `maxFiles: 1` worked as I expected (It created 1 rotated file) before I added path. But anyway I'll try and write about result here.

**Comment by iccicci** [comment]
Never mind, @painkkiller ; what you noticed (and reported in your last comment) is enough.
Thank you

**Comment by painkkiller** [comment]
@iccicci I've tried `maxFiles: 2` and got the same result

**Comment by iccicci** [comment]
Hi @painkkiller , I tried to reproduce the reported problem, but I wasn't able to.

To investigate your problem I suggest to check if the value of `fileName` and `logPath` are the ones you actually expect.
More than this I suggest to attach liteners to the `error` and `warning` events emitted by `rfs`.
You could also check the content of the _history file_ to check if it is congruent with `ls` output.

Hope this helps.

**Comment by iccicci** [comment]
Hi @painkkiller ,

have you tried listening `error` and `warning` events?

**Comment by painkkiller** [comment]
Hi! Sorry for not responding, I had other tasks. I've checked looks everything works fine. Problem was I created stream inside function, when I moved it outside everything starts to work fine.

**Comment by painkkiller** [comment]
Issue can be closed

**Comment by iccicci** [comment]
The only thing which matters is: you was able to solve the probelm! 😄 
Thank you
