### ISSUE TITLE
Unhandled Error, No such file or directory, unlink called twice on same file. 

### ISSUE THREAD

**Issue by mai1x9** [iccicci/rotating-file-stream#88]
```
Error: ENOENT: no such file or directory, unlink '/home/lns_vm05/logs/admin/http/access.log'
Emitted 'error' event on RotatingFileStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/home/lns_vm05/logs/admin/http/access.log'
}
```

The logs are saved at `access.log`, however looks like `unlink` had thrown the error `No file or directroy`. Looks like the log file might have been gzipped, and removed by rotating log file, but above error is thrown for some strange reasons. May be twice calling in code to unlink ?

**Comment by mai1x9** [comment]
It could be a possibility that `maxFiles`, and `maxSize` conditions are both satsified and they both try to remove the same file. Since maxFiles already removes the file, looks like  maxSize throws error. From the code, 
https://github.com/iccicci/rotating-file-stream/blob/b5d6facc1248702a92b9768437c5895c25bc12b1/index.ts#L515

```
    if(maxFiles) {
      while(res.length > maxFiles) {
        const file = res.shift();

        await unlink(file.name);
        this.emit("removed", file.name, true);
      }
    }

    if(maxSize) {
      while(res.reduce((size, file) => size + file.size, 0) > maxSize) {
        const file = res.shift();

        await unlink(file.name);
        this.emit("removed", file.name, false);
      }
    }

```
Both the if conditions are satisfied, and `await unlink(file.name);` throws error when called for second time, since the first call has already removed the file.

**Comment by iccicci** [comment]
Hi @mai1x9 ,

thank you for the detaild report.
I'll check this ASAP!

Thank you

**Comment by iccicci** [comment]
Hi @mai1x9 ,

at a first check I would say the source of the error is not what you assumed: the `const file = res.shift();` before each `await unlink(file.name);` should prevent exactly the same file is tried to be unlinked twice.

More than this, the name of the not existing unlinked file seems to be the _not rotated filename_ not a _rotated filename_.

Could it be you are using an external compression command which removes the file? Please check the last **note** if [this paragraph](https://github.com/iccicci/rotating-file-stream#compress).

If that's not the case, could you please share the portion of your code relevat for **rotating-file-stream**?

Thank you

**Comment by mai1x9** [comment]
the options I have used,
```
let accessLogStream = () =>
  rfs.createStream(  
     access.log , // filename like access.log etc..
    {
      size: '10M', // rotate every 10 MegaBytes written
      interval: '1d', // rotate daily
      compress: "gzip", // compress rotated files
      maxFiles: 8,
      maxSize: "25M",
      path: "admin", // folder where the log file as well as rotated files will be saved
      // rotated files will be saved as yyyy-mm-dd-time-<FILENAME>.log
      // Filename: 20221230-0639-13-access.log
    }
  );
```
I have used it along with Morgan while integrating logging with express.

**Comment by iccicci** [comment]
It's really hard to identify the sourse of this problem with these data.

I could suggest you to listen for the `error` and `warning` events the stream can emit; this could help you to identify the problem.

Anyway this issue is suggesting me that a `ENOENT` error while unlinking a file should be threated as a warning; I'll work on an upgrade in this direction.

**Comment by iccicci** [comment]
Hi @mai1x9 ,

I've just released v3.1.0 with the update I told a while ago. It may help on your problem.

Please give me some feedback, even if can take some weeks.

Thank you

**Comment by mai1x9** [comment]
Hi @iccicci i havent checked the new version yet, however I am unable to liten for error event too.


> @iccicci thanks for clarification, I wonder why the error has occurred.
> 
> the options I have used,
> 
> ```
> let accessLogStream = () =>
>   rfs.createStream(  
>      access.log , // filename like access.log etc..
>     {
>       size: '10M', // rotate every 10 MegaBytes written
>       interval: '1d', // rotate daily
>       compress: "gzip", // compress rotated files
>       maxFiles: 8,
>       maxSize: "25M",
>       path: "admin", // folder where the log file as well as rotated files will be saved
>       // rotated files will be saved as yyyy-mm-dd-time-<FILENAME>.log
>       // Filename: 20221230-0639-13-access.log
>     }
>   );
> ```
> 
> I have used it along with Morgan while integrating logging with express.
> 
> Could it be due to `compress` function call at
> 
> https://github.com/iccicci/rotating-file-stream/blob/b5d6facc1248702a92b9768437c5895c25bc12b1/index.ts#L455
> 
> The issue is hard to reproduce. I could get this error after running server for more than 2 weeks and suddenly server crashed.

I have tried using 
```
accessLogStream().on("error", (err) => WRTIE TO FILE to capture error
```
But it could not listen on error event and got crashed.  ? Can you please tell me how to capture error event and prevent from crashing.

**Comment by iccicci** [comment]
Hi @mai1x9 ,

that's the correct why to listen for errors and warnings, but I feel there is something strange: if you call twice `accessLogStream()` you get two distinct streams so events fired by one of them is not listened by handlers atcched to the other one.

I suggest to make sure your code looks like follows.

```
const getAccessLogStream = () => rfs.createStream("access.log", { ... });

const accessLogStream = getAccessLogStream();

accessLogStream.on("error", error => ... );
accessLogStream.on("warning", warning => ... );

app.use(morgan("combined", { stream: accessLogStream }));
```

I hope this helps.

**Comment by mai1x9** [comment]
> Hi @mai1x9 ,
> 
> that's the correct way to listen for errors and warnings, but I feel there is something strange: if you call twice `accessLogStream()` you get two distinct streams so events fired by one of them is not listened by handlers attached to the other one.
> 
> I suggest to make sure your code looks like follows.
> 
> ```
> const getAccessLogStream = () => rfs.createStream("access.log", { ... });
> 
> const accessLogStream = getAccessLogStream();
> 
> accessLogStream.on("error", error => ... );
> accessLogStream.on("warning", warning => ... );
> 
> app.use(morgan("combined", { stream: accessLogStream }));
> ```
> 
> I hope this helps.

I think what you have suggested make sense, i guess i might have called `getAccessLogStream ()` twice somewhere in the code, as a result the unlink error might have raised, since both of them might have tried to unlink at almost same time(may be a race condition sort of). The second stream is executing unlink, but just before it unlinks, may be first stream might have unlinked, and hence the error.

**Comment by iccicci** [comment]
It could be! As I said  [here](https://github.com/iccicci/rotating-file-stream/issues/88#issuecomment-1423760116), the most likely option is something else which is deleting the file: another **rotating-file-stream** with the same configuration has exactly the same effect.

**Comment by iccicci** [comment]
Hi @mai1x9 , was you able to solve your issue?
Thank you

**Comment by mai1x9** [comment]
> Hi @mai1x9 , was you able to solve your issue? Thank you

yes indeed i guess the issue was 2 different process was calling same rotating stream log, if one process rotates logs the other process results in no file found error. 

After updating the radiating log filename for different processes its working indeed

**Comment by iccicci** [comment]
For sure opening twice the same file is not a good idea.
To use the package with `cluster` module I would say it's mandatory to open a different file from each child process, something like using the pid as part of the file name; i.e. using the pid in the generator file name function.

**Comment by mai1x9** [comment]
> For sure opening twice the same file is not a good idea. To use the package with `cluster` module I would say it's mandatory to open a different file from each child process, something like using the pid as part of the file name; i.e. using the pid in the generator file name function.

Yes I was thinking the same, but can code be updated such that when file is not found, it try to figure out if any other log file exists and then write to it instead.

**Comment by iccicci** [comment]
Hm no, I'm not planning nothing similar...
I'm planning some refactoring, but nothing in this direction.
Here the problem is clear and must be solved removing the root cause, adding a workaround for this problem, from my point of view, doesn't sound as a good idea.

**Comment by mai1x9** [comment]
Ok will go for workaround. But I guess managing the logs might be difficult since we end up with many files and logs might be out of order when analyzing , especially in distributed environments.
