### ISSUE TITLE
The first rotated file is not specified time length.

### ISSUE THREAD

**Issue by rick-yhchen1013** [iccicci/rotating-file-stream#89]
The rotate seems aligned with system time.
Is it possible to rotate the file exactly with specified time inteval?

suppose the inteval is 60s
if user start to use the file stream at clock 09:38:24, the first file is saved in clock 09:39:24, the second file is saved in clock 09:40:24.
And the file size of each file are roughly the same size if the stream of data is continuous the same amount per period of time.

**Comment by iccicci** [comment]
Nope @rick-yhchen1013 , that option is not present, sorry.
