### ISSUE TITLE
Error: this.timeout.unref is not a function

### ISSUE THREAD

**Issue by viniciusteixeiradias** [iccicci/rotating-file-stream#90]
Guys, I installed this lib in my project to help me with the log storage work, but I'm stuck in an error.
I added the simplest configuration to my project and every time I see the system compile, I get the following error:

<img width="405" alt="Screenshot 2023-03-09 at 7 57 21 pm" src="https://user-images.githubusercontent.com/69281620/223986976-da0aa1e0-dfbd-4c5e-9cdb-f5c19056c14c.png">
I could be doing some wrong configuration, I already looked in the doc and in other issues but I didn't find it, I hope you can help me :).

My code:

```ts
import { Logger, ILogObj } from "tslog";
import { createStream } from "rotating-file-stream";

const stream = createStream('tslog.log', {
  size: "10M", // rotate every 10 MegaBytes written
  compress: "gzip", // compress rotated files
  interval: "1d",
});

const logger: Logger<ILogObj> = new Logger({ type: "hidden", hideLogPositionForProduction: true });
logger.attachTransport((logObj) => {
  stream.write(JSON.stringify(logObj) + "\n");
});
```

**Comment by iccicci** [comment]
Hi @viniciusteixeiradias ,

this is very strange!
[This](https://github.com/iccicci/rotating-file-stream/blob/master/index.ts#L437-L438) is the only call to `unref` in the source code.

Could it be, in your project, something replaces the `setTimeout` builtin function?

**Comment by viniciusteixeiradias** [comment]
@iccicci I don't think it can be in my code. I'll check the project settings, but today the "rotating-file-stream" code is just this:

```
import type { InjectionKey } from 'vue'
import { Logger, ILogObj } from "tslog";
import { createStream } from "rotating-file-stream";

const stream = createStream('tslog.log', {
  size: "10M",
  compress: "gzip",
  interval: '1d',
});

const logger: Logger<ILogObj> = new Logger({ type: "hidden", hideLogPositionForProduction: true });
logger.attachTransport((logObj) => {
  stream.write(JSON.stringify(logObj) + "\n");
});

const key = Symbol() as InjectionKey<Logger<ILogObj>>

export { logger, key };
```

**Comment by iccicci** [comment]
The portion of code you pasted is fine, TypeScript is fine, I don't know vue, but it should be fine as well.

When I spoken about your project I was not speaking directly about your code, maybe some other packages...

Please check this [two lines](https://github.com/iccicci/rotating-file-stream/blob/master/index.ts#L437-L438) of code; the built-in `setTimeout` function returns an object which has an `unref` method, the only explaination coming to my mind for the problem is you reported is that something replaced the built-in `setTimeout` function with anouther function which returns something else.

**Comment by viniciusteixeiradias** [comment]
I created a project from scratch to validate if the error still persists. The error remains the same, if you want to test:
https://github.com/viniciusteixeiradias/issue-rotate-file-system

The rotate-file-system config
https://github.com/viniciusteixeiradias/issue-rotate-file-system/blob/main/src/App.vue

**Comment by iccicci** [comment]
https://stackoverflow.com/a/54785005/4690946

**Comment by leviplj** [comment]
@iccicci , quick question... Does `rotating-file-stream` run on the browser?

**Comment by iccicci** [comment]
Nope @leviplj , it is designed only for Node.js, it doesn't implement writing files from browsers.

**Comment by viniciusteixeiradias** [comment]
@iccicci "Universal: Works in Browsers and Node.js"?
<img width="452" alt="Screenshot 2023-03-10 at 10 00 27 pm" src="https://user-images.githubusercontent.com/69281620/224311073-937c83af-7dac-4c55-85ec-f20dd2dc591d.png">

**Comment by viniciusteixeiradias** [comment]
@iccicci "Universal: Works in Browsers and Node.js"?
<img width="452" alt="Screenshot 2023-03-10 at 10 00 27 pm" src="https://user-images.githubusercontent.com/69281620/224311572-8cc847b3-0ea4-4fc2-947b-e8d41d3f0675.png">

**Comment by iccicci** [comment]
@viniciusteixeiradias I don't know universal

**Comment by viniciusteixeiradias** [comment]
@iccicci Yes sorry. It's just that I was using the ts-log lib and they indicate using rotate-file-system, ts-log runs in browsers, but apparently rotate-file-system does not. The only problem I had was with the interval, but since it's not browser compatible, I closed the issue.
