### ISSUE TITLE
Jumping from Node v14 to v18 between 3.1.1 and 3.2.0

### ISSUE THREAD

**Issue by gh-andre** [iccicci/rotating-file-stream#98]
Some of us cannot go to Node 18 just yet and will need stop updates at v3.1.1, until Node v18 becomes available on relevant platforms. For example, on CentOS 9 only Node v16 is available through the official update channels. I realize that Node v16 is no longer supported, but as of a few hours ago this package was running just fine on Node v14. Is it not possible to use the next LTS after v14, which is Node v16?

The README still says Node v14, BTW.

**Comment by iccicci** [comment]
I forgot to update the README; thank you.

Anyway v3.2.0 simply adds [intervalUTC](https://github.com/iccicci/rotating-file-stream#intervalutc) option: if that's not needed, v3.2.0 is not needed as well.

BTW, older Node.js versions _should_ be supported as well; forcing the installation of v3.2.0 reguardless from the engine version should make everything work as expected.

**Comment by gh-andre** [comment]
Thanks for responding.

> older Node.js versions should be supported as well

`npm` will report a warning that the package requests an unsupported engine version, so the only safe thing to do is to avoid installing that package version and limit it to something like `3.1.*`.

**Comment by iccicci** [comment]
The only reason for the warning is [this line](https://github.com/iccicci/rotating-file-stream/blob/master/package.json#L22): indeed is just a warning, not a blocking error.

In next days, I'll re-add support for Node.js v14; I hope this doesn't block your work even if for a few days.

**Comment by gh-andre** [comment]
No worries - I restricted package version in my projects to `3.1.*`, so I'm good for quite a while.

With regards to warning vs. error, perhaps there's a difference in interpretation, where those who treat this warning as such consider that the package in question _will work with_ this version of Node, while it really means that the package _requires_ this version because it introduces dependencies that the package requires, like new classes, encodings, etc. So, even though it's a warning, it is always a good practice to avoid installing packages that require higher version of Node than the current one.

Thanks for contemplating a fix for this. Much appreciated.

**Comment by iccicci** [comment]
Hi @gh-andre , v3.2.1 should solve this.

Please report here any other problems or close the issue if v3.2.1 actually solves.

Thank you

**Comment by gh-andre** [comment]
@iccicci It works now - no warning when installing 3.2.1. Thank you!
