### ISSUE TITLE
maxfiles seems to cause an error: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by pxbos19** [iccicci/rotating-file-stream#99]
My configuration is as follows:
log.js :

function pad(number) {
  return number < 10 ? '0' + number.toString() : number.toString();
}

function generator(time) {
  if (!time) return 'cmt.log';
  const year = time.getFullYear();
  const month = pad(time.getMonth() + 1);
  const day = pad(time.getDate());

  return `cmt.${year}-${month}-${day}.log`;
}

// 创建一个流
const accessLogStream = rfs.createStream(generator, {
  interval: '1d', // 每天旋转
  path: './mnt/log',
  maxfiles: 3
});

When four log files are generated in the mnt\log directory：
cmt.log
cmt.2024-02-04.log
cmt.2024-02-05.log
cmt.2024-02-06.log

An error occurred:
Error: ENOENT: no such file or directory, rename 'xxx\mnt\log\cmt.log' -> 'xxx\mnt\log\cmt.2024-02-04.log'

Why does this problem occur? The effect I want is to keep the log file for 3 days, and delete the earliest time after 3 days to generate a new log file for the day.

**Comment by iccicci** [comment]
Hi @pxbos19 , that is the right cfg to achieve your target...

Do you have a stack trace of the error?

I also suggest to cjeck the `error` and `warning` events, they can help you understanding better...

```
accessLogStream.on("error", console.log);
accessLogStream.on("warning", console.log);
```

**Comment by pxbos19** [comment]
![图像](https://github.com/iccicci/rotating-file-stream/assets/155933151/aa490d76-95cf-43e4-b8fd-7054a4afcf16)
I tested it by generating a log file at intervals of 30 seconds. When I judged whether the file existed, the file had not been generated yet, which resulted in an error.

**Comment by iccicci** [comment]
Sorry, but this doesn't help identifying the problem.

Could it be you initialize twice the rfs?
In such case the first one will perform the rotation the second one gets
the error.

Hope this helps
